version: '3'
services:
  apache:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf
#      - /opt/homebrew/etc/httpd/httpd.conf:/usr/local/apache2/conf

  auth_node:
    build:
      context: ./node
      dockerfile: AuthDockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./node:/app
    depends_on:
      - mongodb

  article_node:
    build:
      context: ./node
      dockerfile: AuthDockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
    depends_on:
      - mongodb

  ads_node:
    build:
      context: ./node
      dockerfile: AuthDockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./node:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /opt/homebrew/var/mongodb:/data/db
