version: '3'
services:
  apache:
    build:
      context: ./httpd
    ports:
      - "80:80"
    depends_on:
      - auth_node
      - article_node
      - ads_node

  auth_node:
    build:
      context: ./node
      dockerfile: AuthDockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./node:/app
    depends_on:
      - mongodb

  article_node:
    build:
      context: ./node
      dockerfile: ArticleDockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./node:/app
    depends_on:
      - mongodb

  ads_node:
    build:
      context: ./node
      dockerfile: AdsDockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./node:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /opt/homebrew/var/mongodb:/data/db
